variables:

cache:
  key: "general"
  paths:
    - vendor/
    - .php_cs.cache

stages:
  - test

test:
  stage: test
  only: [merge_requests, "/master/"]
  image: zantolov/docker-symfony-php-fpm:7.3
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - chmod 700 ~/.ssh
    - ssh-add -l
    - composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader
    - composer validate --no-check-publish --no-interaction --ansi
    - composer run lint
    - composer run qc
    - composer run test
