cache:
    key: "$CI_PIPELINE_ID"
    paths:
        - vendor/

stages:
    - build

build:docker:
    stage: build
    only: [merge_requests, "/master/"]
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker build -f docker/Dockerfile .
