name: json-api-symfony

on: [push, pull_request]

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USER }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build work image
        run: |
          docker build -f ./docker/Dockerfile --build-arg XDEBUG_ENABLED="false" .
#          docker build -f docker/Dockerfile.dev --build-arg XDEBUG_ENABLED="false" -t undabot/json-api-symfony:latest
#      - name: Push image to DockerHub
#        run: |
#          docker push undabot/json-api-symfony:latest


#  test_image:
#    runs-on: ubuntu-latest
#    needs: [build_image]
#    container: 
#        image: json-api-symfony:latest
#    steps:
#      - name: Test image
#        run: |
#          cd /opt/app
#          composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader
#          composer validate --no-check-publish --no-interaction --ansi
#          composer run lint
#          composer run qc
#          phpdbg -qrr ./vendor/bin/phpunit
#          cat tests/_reports/coverage.txt | head -n 10 | grep "Lines"